Repository warmachine028/HR-Chatbot, pull requests merged in 2024-06, with the labels that each got.

#5 docs: added licencee
  .github/labels.yml
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
Labels: documentation, 📄 aspect: text

#6 feat: added data.csv
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/first-contribution.yml
  .github/workflows/greet-contributors.yml
  CONTRIBUTING.md
  GUIDELINES.md
  README.md
  src/data.csv
  src/test
Labels: enhancement, feature

#9 feat: added model demo
  .github/workflows/codeql-analysis.yml
  src/Model.ipynb
  src/Scripts/Activate.ps1
  src/Scripts/activate
  src/Scripts/activate.bat
  src/Scripts/deactivate.bat
  src/Scripts/f2py.exe
  src/Scripts/ipython.exe
  src/Scripts/ipython3.exe
  src/Scripts/jupyter-kernel.exe
  src/Scripts/jupyter-kernelspec.exe
  src/Scripts/jupyter-migrate.exe
  src/Scripts/jupyter-run.exe
  src/Scripts/jupyter-troubleshoot.exe
  src/Scripts/jupyter.exe
  src/Scripts/pip.exe
  src/Scripts/pip3.12.exe
  src/Scripts/pip3.exe
  src/Scripts/pygmentize.exe
  src/Scripts/python.exe
  src/Scripts/pythonw.exe
  src/Scripts/pywin32_postinstall.py
  src/Scripts/pywin32_testall.py
  src/help.sh
  src/knowledge_base.csv
  src/pyvenv.cfg
  src/requirements.txt
  src/share/jupyter/kernels/python3/kernel.json
  src/share/jupyter/kernels/python3/logo-32x32.png
  src/share/jupyter/kernels/python3/logo-64x64.png
  src/share/jupyter/kernels/python3/logo-svg.svg
  src/share/man/man1/ipython.1
Labels: enhancement, feature

#11 fix: codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: 🛠 goal: fix, 🐞 bug

#12 fix: codeql-analysis
  .github/workflows/updateDate.sh
Labels: 🛠 goal: fix, 🐞 bug

#20 docs: updated knowledge_base.csv
  src/knowledge_base.csv
Labels: documentation, 📄 aspect: text

#24 feat: added demo NLP Model
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .gitignore
  .prettierrc
  src/Model.ipynb
  src/client/.eslintrc.cjs
  src/client/.gitignore
  src/client/README.md
  src/client/index.html
  src/client/package-lock.json
  src/client/package.json
  src/client/postcss.config.js
  src/client/public/vite.svg
  src/client/src/App.css
  src/client/src/App.jsx
  src/client/src/assets/react.svg
  src/client/src/index.css
  src/client/src/main.jsx
  src/client/tailwind.config.js
  src/client/vite.config.js
  src/python/Model.ipynb
  src/python/Model.py
  src/python/help.sh
  src/python/intents.json
  src/python/knowledge_base.csv
  src/python/requirements.txt
  src/server/app.py
  src/server/requirements.txt
  src/test/NLP.ipynb
  src/test/data.pth
  src/test/requirements.txt
Labels: enhancement, feature

#26 feat: added login page
  src/Login_Page/Chatbot.code-workspace
  src/Login_Page/images/Day.jpg
  src/Login_Page/images/Night.jpg
  src/Login_Page/images/moon.png
  src/Login_Page/images/sun.png
  src/Login_Page/index.html
  src/Login_Page/script.js
  src/Login_Page/styles.css
Labels: enhancement, feature
